[package]
name = "http_load"
version = "0.1.0"
authors = ["John McDonnell <john.mcdonnell439@gmail.com>"]

[dependencies]
time = "0.1.40"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"